# Generated by Django 3.1.3 on 2020-11-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delito', models.CharField(choices=[('asesinato', 'Asesinato'), ('homicidio', 'Homicidio'), ('robo', 'Robo'), ('hurto', 'Hurto'), ('lesiones', 'Lesiones')], max_length=200, verbose_name='Tipo de delito')),
                ('antecedentes', models.BooleanField(verbose_name='Antecendentes del acusado')),
                ('supuestos', models.CharField(choices=[('el acusado recibió dinero', 'Dinero'), ('el acusado sufre incapacidad mental', 'Incapacidad'), ('fue en defensa propia', 'Defensa Propia'), ('historial de abusos', 'Historial Abusos'), ('menos de 400€', 'Menos 400'), ('más de 400€', 'Mas 400')], max_length=200, verbose_name='Supuestos de hecho')),
                ('procedencia', models.CharField(choices=[('Madrid', 'Madrid'), ('Barcelona', 'Barcelona'), ('Valencia', 'Valencia'), ('Bilbao', 'Bilbao')], max_length=200, verbose_name='Lugar de procedencia del acusado')),
                ('sentencia', models.CharField(choices=[('absolución', 'Absolucion'), ('multa', 'Multa'), ('2 años de cárcel', 'Carcel 2'), ('20 años de cárcel', 'Carcel 20')], max_length=200, verbose_name='Sentencia')),
                ('nombre_juez', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del juez')),
                ('dataset', models.CharField(blank=True, choices=[('training', 'Training'), ('test', 'Test')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Juicios',
            },
        ),
    ]
